### ISSUE TITLE
Options for some extra rules

### ISSUE THREAD

**Issue by BaboKiwi** [oli-69/schwimmen#1]
Is it possible to add some extra rules and optional choose these per checkbox?

optional rule for "Tausche Karten" -> cards 7, 8, 9 are allowed to exchange with new cards
optional rule for "Schieben" -> each player is allowed to choose "Schieben" only once

thanks in advance

**Comment by oli-69** [comment]
Hi,
many thanks for this suggestions.

As soon there is a little bit time left, i will implement it. Hopefully within the next few days.

Cheers

________________________________
Von: BaboKiwi <notifications@github.com>
Gesendet: Samstag, 23. Januar 2021 17:45
An: oli-69/schwimmen <schwimmen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [oli-69/schwimmen] Options for some extra rules (#1)


Is it possible to add some extra rules and optional choose these per checkbox?

optional rule for "Tausche Karten" -> cards 7, 8, 9 are allowed to exchange with new cards
optional rule for "Schieben" -> each player is allowed to choose "Schieben" only once

thanks in advance

**Comment by BaboKiwi** [comment]
Hi,
that sounds great!

By the way...we have played the game on saturday with friends in Switzerland, which
we cannot see this ski vacation.
It was a lot of fun and so easy to setup. There was a lot of drinking and laughing,
a great distraction at this pandemic time.

Thanks again for your successful implementation.  :-)

**Comment by BaboKiwi** [comment]
Hi,
I just noticed that the first suggestion could be misunderstood...
It should  be an optional rule for "Neue Karten", not for "Tausche Karten"  ;-)

Cheers

**Comment by oli-69** [comment]
Hi, 
I've commited the optional game rules and added a binary release also.
Thank you for testing it! ;-)
Cheers

**Comment by BaboKiwi** [comment]
Hi,
you've done a great job, both rules work! :-)

There is only a small discrepancy with the button "Schieben":
If the button is pressed, it is not grayed out the next time
to indicate that it can no longer be used.
(It can be pushed down, luckily it doesn't do anything.)

Cheers

**Update**:
After testing again today, everything looks fine. :-)
Maybe the browser still had something in the cache (?) in the previous test..

So everything is ok and the issue can be closed.

Again, thanks a lot!
