### ISSUE TITLE
A round ends too early after the second "Klopfen"

### ISSUE THREAD

**Issue by BaboKiwi** [oli-69/schwimmen#2]
I've noticed that the round will end directly after the second "Klopfen".

In my opinion, after the first "Klopfen", all players have to take their turn again, even if another "Klopfen" is made.

But could be a optional rule, too.

thanks in advance

**Comment by oli-69** [comment]
Hi BaboKiwi,
the second "Klopfen" is an important part of the game in my understanding (and my friends as well). Furthermore, disabling it, wouldn't fit well together with the optional game rule "pass once". Hence I will not put any effort into it. Of course you are welcome to implement it.
Regards

**Comment by BaboKiwi** [comment]
Hi,
maybe you have already noticed ... I uploaded an implementation for having knock rules as an option.
You can find the additions/changes in my fork in branch babokiwi.
Regards

**Comment by oli-69** [comment]
Hi,

Hi, you made a lot of changes. Great! I am impressed that you could understand the code, especially the JavaScript part ;-)

Cheers

________________________________
Von: BaboKiwi <notifications@github.com>
Gesendet: Samstag, 6. März 2021 12:59
An: oli-69/schwimmen <schwimmen@noreply.github.com>
Cc: Oliver <ofh3@hotmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [oli-69/schwimmen] A round ends too early after the second "Klopfen" (#2)


Hi,
maybe you have already noticed ... I uploaded an implementation for having knock rules as an option.
You can find the additions/changes in my fork in branch babokiwi.
Regards

**Comment by oli-69** [comment]
I reviewed your extension and wanted to merge it to the master branch. Unfortunately some tests failed and I rolled back. Anyway, great job!

**Comment by BaboKiwi** [comment]
Hi Oli,

I've analyzed the test file and I think that the activation of the knocking rules is missing in three test cases, so these tests fail.

You can find the updated test file in my branch babokiwi.

CU
Babo

**Comment by oli-69** [comment]
Hi Babo,
I've recently merged your work into the main branch.
Thanks for your help!
